"""交易信号模型 / Trade Signal Models"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field


class SignalType(str, Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class TradeSignal(BaseModel):
    """交易信号 / Trade signal generated by strategy engine"""
    symbol: str
    signal_type: SignalType
    price: float
    quantity: float = 0.0
    strategy_name: str = ""
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    reason: str = ""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
